# Generated by Django 2.1.1 on 2018-09-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('auth', 'Waiting for authorisation'), ('failed', 'Failed'), ('completed', 'Completed')])),
                ('amount_cents', models.IntegerField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinweb.Account')),
            ],
        ),
    ]
